EXPLAIN (FORMAT JSON, ANALYZE, VERBOSE)
select s_name, s_address from supplier, nation where s_suppkey in ( select ps_suppkey from partsupp where ps_partkey in ( select p_partkey from part where p_name like 'ivory%' ) and ps_availqty > ( select 0.5 * sum(l_quantity) from lineitem where l_partkey = ps_partkey and l_suppkey = ps_suppkey and l_shipdate >= date '1996-01-01' and l_shipdate < date '1996-01-01' + interval '1 year' ) ) and s_nationkey = n_nationkey and n_name =  'KENYA' order by s_name;
EXPLAIN (FORMAT JSON, ANALYZE, VERBOSE)
select s_name, s_address from supplier, nation where s_suppkey in ( select ps_suppkey from partsupp where ps_partkey in ( select p_partkey from part where p_name like 'seashell%' ) and ps_availqty > ( select 0.5 * sum(l_quantity) from lineitem where l_partkey = ps_partkey and l_suppkey = ps_suppkey and l_shipdate >= date '1994-01-01' and l_shipdate < date '1994-01-01' + interval '1 year' ) ) and s_nationkey = n_nationkey and n_name =  'EGYPT' order by s_name;
EXPLAIN (FORMAT JSON, ANALYZE, VERBOSE)
select s_name, s_address from supplier, nation where s_suppkey in ( select ps_suppkey from partsupp where ps_partkey in ( select p_partkey from part where p_name like 'dim%' ) and ps_availqty > ( select 0.5 * sum(l_quantity) from lineitem where l_partkey = ps_partkey and l_suppkey = ps_suppkey and l_shipdate >= date '1993-01-01' and l_shipdate < date '1993-01-01' + interval '1 year' ) ) and s_nationkey = n_nationkey and n_name =  'ROMANIA' order by s_name;
EXPLAIN (FORMAT JSON, ANALYZE, VERBOSE)
select s_name, s_address from supplier, nation where s_suppkey in ( select ps_suppkey from partsupp where ps_partkey in ( select p_partkey from part where p_name like 'papaya%' ) and ps_availqty > ( select 0.5 * sum(l_quantity) from lineitem where l_partkey = ps_partkey and l_suppkey = ps_suppkey and l_shipdate >= date '1996-01-01' and l_shipdate < date '1996-01-01' + interval '1 year' ) ) and s_nationkey = n_nationkey and n_name =  'INDIA' order by s_name;
EXPLAIN (FORMAT JSON, ANALYZE, VERBOSE)
select s_name, s_address from supplier, nation where s_suppkey in ( select ps_suppkey from partsupp where ps_partkey in ( select p_partkey from part where p_name like 'blue%' ) and ps_availqty > ( select 0.5 * sum(l_quantity) from lineitem where l_partkey = ps_partkey and l_suppkey = ps_suppkey and l_shipdate >= date '1995-01-01' and l_shipdate < date '1995-01-01' + interval '1 year' ) ) and s_nationkey = n_nationkey and n_name =  'UNITED KINGDOM' order by s_name;
EXPLAIN (FORMAT JSON, ANALYZE, VERBOSE)
select s_name, s_address from supplier, nation where s_suppkey in ( select ps_suppkey from partsupp where ps_partkey in ( select p_partkey from part where p_name like 'linen%' ) and ps_availqty > ( select 0.5 * sum(l_quantity) from lineitem where l_partkey = ps_partkey and l_suppkey = ps_suppkey and l_shipdate >= date '1993-01-01' and l_shipdate < date '1993-01-01' + interval '1 year' ) ) and s_nationkey = n_nationkey and n_name =  'JORDAN' order by s_name;
EXPLAIN (FORMAT JSON, ANALYZE, VERBOSE)
select s_name, s_address from supplier, nation where s_suppkey in ( select ps_suppkey from partsupp where ps_partkey in ( select p_partkey from part where p_name like 'tan%' ) and ps_availqty > ( select 0.5 * sum(l_quantity) from lineitem where l_partkey = ps_partkey and l_suppkey = ps_suppkey and l_shipdate >= date '1997-01-01' and l_shipdate < date '1997-01-01' + interval '1 year' ) ) and s_nationkey = n_nationkey and n_name =  'CANADA' order by s_name;
EXPLAIN (FORMAT JSON, ANALYZE, VERBOSE)
select s_name, s_address from supplier, nation where s_suppkey in ( select ps_suppkey from partsupp where ps_partkey in ( select p_partkey from part where p_name like 'ghost%' ) and ps_availqty > ( select 0.5 * sum(l_quantity) from lineitem where l_partkey = ps_partkey and l_suppkey = ps_suppkey and l_shipdate >= date '1995-01-01' and l_shipdate < date '1995-01-01' + interval '1 year' ) ) and s_nationkey = n_nationkey and n_name =  'PERU' order by s_name;
EXPLAIN (FORMAT JSON, ANALYZE, VERBOSE)
select s_name, s_address from supplier, nation where s_suppkey in ( select ps_suppkey from partsupp where ps_partkey in ( select p_partkey from part where p_name like 'red%' ) and ps_availqty > ( select 0.5 * sum(l_quantity) from lineitem where l_partkey = ps_partkey and l_suppkey = ps_suppkey and l_shipdate >= date '1993-01-01' and l_shipdate < date '1993-01-01' + interval '1 year' ) ) and s_nationkey = n_nationkey and n_name =  'GERMANY' order by s_name;
EXPLAIN (FORMAT JSON, ANALYZE, VERBOSE)
select s_name, s_address from supplier, nation where s_suppkey in ( select ps_suppkey from partsupp where ps_partkey in ( select p_partkey from part where p_name like 'coral%' ) and ps_availqty > ( select 0.5 * sum(l_quantity) from lineitem where l_partkey = ps_partkey and l_suppkey = ps_suppkey and l_shipdate >= date '1997-01-01' and l_shipdate < date '1997-01-01' + interval '1 year' ) ) and s_nationkey = n_nationkey and n_name =  'RUSSIA' order by s_name;
EXPLAIN (FORMAT JSON, ANALYZE, VERBOSE)
select s_name, s_address from supplier, nation where s_suppkey in ( select ps_suppkey from partsupp where ps_partkey in ( select p_partkey from part where p_name like 'moccasin%' ) and ps_availqty > ( select 0.5 * sum(l_quantity) from lineitem where l_partkey = ps_partkey and l_suppkey = ps_suppkey and l_shipdate >= date '1995-01-01' and l_shipdate < date '1995-01-01' + interval '1 year' ) ) and s_nationkey = n_nationkey and n_name =  'IRAQ' order by s_name;
EXPLAIN (FORMAT JSON, ANALYZE, VERBOSE)
select s_name, s_address from supplier, nation where s_suppkey in ( select ps_suppkey from partsupp where ps_partkey in ( select p_partkey from part where p_name like 'almond%' ) and ps_availqty > ( select 0.5 * sum(l_quantity) from lineitem where l_partkey = ps_partkey and l_suppkey = ps_suppkey and l_shipdate >= date '1994-01-01' and l_shipdate < date '1994-01-01' + interval '1 year' ) ) and s_nationkey = n_nationkey and n_name =  'ARGENTINA' order by s_name;
EXPLAIN (FORMAT JSON, ANALYZE, VERBOSE)
select s_name, s_address from supplier, nation where s_suppkey in ( select ps_suppkey from partsupp where ps_partkey in ( select p_partkey from part where p_name like 'khaki%' ) and ps_availqty > ( select 0.5 * sum(l_quantity) from lineitem where l_partkey = ps_partkey and l_suppkey = ps_suppkey and l_shipdate >= date '1997-01-01' and l_shipdate < date '1997-01-01' + interval '1 year' ) ) and s_nationkey = n_nationkey and n_name =  'MOZAMBIQUE' order by s_name;
EXPLAIN (FORMAT JSON, ANALYZE, VERBOSE)
select s_name, s_address from supplier, nation where s_suppkey in ( select ps_suppkey from partsupp where ps_partkey in ( select p_partkey from part where p_name like 'sienna%' ) and ps_availqty > ( select 0.5 * sum(l_quantity) from lineitem where l_partkey = ps_partkey and l_suppkey = ps_suppkey and l_shipdate >= date '1996-01-01' and l_shipdate < date '1996-01-01' + interval '1 year' ) ) and s_nationkey = n_nationkey and n_name =  'FRANCE' order by s_name;
EXPLAIN (FORMAT JSON, ANALYZE, VERBOSE)
select s_name, s_address from supplier, nation where s_suppkey in ( select ps_suppkey from partsupp where ps_partkey in ( select p_partkey from part where p_name like 'dodger%' ) and ps_availqty > ( select 0.5 * sum(l_quantity) from lineitem where l_partkey = ps_partkey and l_suppkey = ps_suppkey and l_shipdate >= date '1994-01-01' and l_shipdate < date '1994-01-01' + interval '1 year' ) ) and s_nationkey = n_nationkey and n_name =  'SAUDI ARABIA' order by s_name;
EXPLAIN (FORMAT JSON, ANALYZE, VERBOSE)
select s_name, s_address from supplier, nation where s_suppkey in ( select ps_suppkey from partsupp where ps_partkey in ( select p_partkey from part where p_name like 'peach%' ) and ps_availqty > ( select 0.5 * sum(l_quantity) from lineitem where l_partkey = ps_partkey and l_suppkey = ps_suppkey and l_shipdate >= date '1997-01-01' and l_shipdate < date '1997-01-01' + interval '1 year' ) ) and s_nationkey = n_nationkey and n_name =  'IRAN' order by s_name;
EXPLAIN (FORMAT JSON, ANALYZE, VERBOSE)
select s_name, s_address from supplier, nation where s_suppkey in ( select ps_suppkey from partsupp where ps_partkey in ( select p_partkey from part where p_name like 'blue%' ) and ps_availqty > ( select 0.5 * sum(l_quantity) from lineitem where l_partkey = ps_partkey and l_suppkey = ps_suppkey and l_shipdate >= date '1996-01-01' and l_shipdate < date '1996-01-01' + interval '1 year' ) ) and s_nationkey = n_nationkey and n_name =  'ALGERIA' order by s_name;
EXPLAIN (FORMAT JSON, ANALYZE, VERBOSE)
select s_name, s_address from supplier, nation where s_suppkey in ( select ps_suppkey from partsupp where ps_partkey in ( select p_partkey from part where p_name like 'magenta%' ) and ps_availqty > ( select 0.5 * sum(l_quantity) from lineitem where l_partkey = ps_partkey and l_suppkey = ps_suppkey and l_shipdate >= date '1994-01-01' and l_shipdate < date '1994-01-01' + interval '1 year' ) ) and s_nationkey = n_nationkey and n_name =  'MOROCCO' order by s_name;
EXPLAIN (FORMAT JSON, ANALYZE, VERBOSE)
select s_name, s_address from supplier, nation where s_suppkey in ( select ps_suppkey from partsupp where ps_partkey in ( select p_partkey from part where p_name like 'thistle%' ) and ps_availqty > ( select 0.5 * sum(l_quantity) from lineitem where l_partkey = ps_partkey and l_suppkey = ps_suppkey and l_shipdate >= date '1993-01-01' and l_shipdate < date '1993-01-01' + interval '1 year' ) ) and s_nationkey = n_nationkey and n_name =  'EGYPT' order by s_name;
EXPLAIN (FORMAT JSON, ANALYZE, VERBOSE)
select s_name, s_address from supplier, nation where s_suppkey in ( select ps_suppkey from partsupp where ps_partkey in ( select p_partkey from part where p_name like 'goldenrod%' ) and ps_availqty > ( select 0.5 * sum(l_quantity) from lineitem where l_partkey = ps_partkey and l_suppkey = ps_suppkey and l_shipdate >= date '1996-01-01' and l_shipdate < date '1996-01-01' + interval '1 year' ) ) and s_nationkey = n_nationkey and n_name =  'ROMANIA' order by s_name;
EXPLAIN (FORMAT JSON, ANALYZE, VERBOSE)
select s_name, s_address from supplier, nation where s_suppkey in ( select ps_suppkey from partsupp where ps_partkey in ( select p_partkey from part where p_name like 'rose%' ) and ps_availqty > ( select 0.5 * sum(l_quantity) from lineitem where l_partkey = ps_partkey and l_suppkey = ps_suppkey and l_shipdate >= date '1995-01-01' and l_shipdate < date '1995-01-01' + interval '1 year' ) ) and s_nationkey = n_nationkey and n_name =  'INDONESIA' order by s_name;
EXPLAIN (FORMAT JSON, ANALYZE, VERBOSE)
select s_name, s_address from supplier, nation where s_suppkey in ( select ps_suppkey from partsupp where ps_partkey in ( select p_partkey from part where p_name like 'coral%' ) and ps_availqty > ( select 0.5 * sum(l_quantity) from lineitem where l_partkey = ps_partkey and l_suppkey = ps_suppkey and l_shipdate >= date '1993-01-01' and l_shipdate < date '1993-01-01' + interval '1 year' ) ) and s_nationkey = n_nationkey and n_name =  'UNITED KINGDOM' order by s_name;
EXPLAIN (FORMAT JSON, ANALYZE, VERBOSE)
select s_name, s_address from supplier, nation where s_suppkey in ( select ps_suppkey from partsupp where ps_partkey in ( select p_partkey from part where p_name like 'navajo%' ) and ps_availqty > ( select 0.5 * sum(l_quantity) from lineitem where l_partkey = ps_partkey and l_suppkey = ps_suppkey and l_shipdate >= date '1996-01-01' and l_shipdate < date '1996-01-01' + interval '1 year' ) ) and s_nationkey = n_nationkey and n_name =  'JORDAN' order by s_name;
EXPLAIN (FORMAT JSON, ANALYZE, VERBOSE)
select s_name, s_address from supplier, nation where s_suppkey in ( select ps_suppkey from partsupp where ps_partkey in ( select p_partkey from part where p_name like 'antique%' ) and ps_availqty > ( select 0.5 * sum(l_quantity) from lineitem where l_partkey = ps_partkey and l_suppkey = ps_suppkey and l_shipdate >= date '1995-01-01' and l_shipdate < date '1995-01-01' + interval '1 year' ) ) and s_nationkey = n_nationkey and n_name =  'CANADA' order by s_name;
EXPLAIN (FORMAT JSON, ANALYZE, VERBOSE)
select s_name, s_address from supplier, nation where s_suppkey in ( select ps_suppkey from partsupp where ps_partkey in ( select p_partkey from part where p_name like 'lace%' ) and ps_availqty > ( select 0.5 * sum(l_quantity) from lineitem where l_partkey = ps_partkey and l_suppkey = ps_suppkey and l_shipdate >= date '1993-01-01' and l_shipdate < date '1993-01-01' + interval '1 year' ) ) and s_nationkey = n_nationkey and n_name =  'CHINA' order by s_name;
EXPLAIN (FORMAT JSON, ANALYZE, VERBOSE)
select s_name, s_address from supplier, nation where s_suppkey in ( select ps_suppkey from partsupp where ps_partkey in ( select p_partkey from part where p_name like 'sky%' ) and ps_availqty > ( select 0.5 * sum(l_quantity) from lineitem where l_partkey = ps_partkey and l_suppkey = ps_suppkey and l_shipdate >= date '1997-01-01' and l_shipdate < date '1997-01-01' + interval '1 year' ) ) and s_nationkey = n_nationkey and n_name =  'GERMANY' order by s_name;
EXPLAIN (FORMAT JSON, ANALYZE, VERBOSE)
select s_name, s_address from supplier, nation where s_suppkey in ( select ps_suppkey from partsupp where ps_partkey in ( select p_partkey from part where p_name like 'drab%' ) and ps_availqty > ( select 0.5 * sum(l_quantity) from lineitem where l_partkey = ps_partkey and l_suppkey = ps_suppkey and l_shipdate >= date '1995-01-01' and l_shipdate < date '1995-01-01' + interval '1 year' ) ) and s_nationkey = n_nationkey and n_name =  'RUSSIA' order by s_name;
EXPLAIN (FORMAT JSON, ANALYZE, VERBOSE)
select s_name, s_address from supplier, nation where s_suppkey in ( select ps_suppkey from partsupp where ps_partkey in ( select p_partkey from part where p_name like 'peru%' ) and ps_availqty > ( select 0.5 * sum(l_quantity) from lineitem where l_partkey = ps_partkey and l_suppkey = ps_suppkey and l_shipdate >= date '1994-01-01' and l_shipdate < date '1994-01-01' + interval '1 year' ) ) and s_nationkey = n_nationkey and n_name =  'JAPAN' order by s_name;
EXPLAIN (FORMAT JSON, ANALYZE, VERBOSE)
select s_name, s_address from supplier, nation where s_suppkey in ( select ps_suppkey from partsupp where ps_partkey in ( select p_partkey from part where p_name like 'blush%' ) and ps_availqty > ( select 0.5 * sum(l_quantity) from lineitem where l_partkey = ps_partkey and l_suppkey = ps_suppkey and l_shipdate >= date '1997-01-01' and l_shipdate < date '1997-01-01' + interval '1 year' ) ) and s_nationkey = n_nationkey and n_name =  'BRAZIL' order by s_name;
EXPLAIN (FORMAT JSON, ANALYZE, VERBOSE)
select s_name, s_address from supplier, nation where s_suppkey in ( select ps_suppkey from partsupp where ps_partkey in ( select p_partkey from part where p_name like 'maroon%' ) and ps_availqty > ( select 0.5 * sum(l_quantity) from lineitem where l_partkey = ps_partkey and l_suppkey = ps_suppkey and l_shipdate >= date '1996-01-01' and l_shipdate < date '1996-01-01' + interval '1 year' ) ) and s_nationkey = n_nationkey and n_name =  'MOZAMBIQUE' order by s_name;
EXPLAIN (FORMAT JSON, ANALYZE, VERBOSE)
select s_name, s_address from supplier, nation where s_suppkey in ( select ps_suppkey from partsupp where ps_partkey in ( select p_partkey from part where p_name like 'tomato%' ) and ps_availqty > ( select 0.5 * sum(l_quantity) from lineitem where l_partkey = ps_partkey and l_suppkey = ps_suppkey and l_shipdate >= date '1994-01-01' and l_shipdate < date '1994-01-01' + interval '1 year' ) ) and s_nationkey = n_nationkey and n_name =  'FRANCE' order by s_name;
EXPLAIN (FORMAT JSON, ANALYZE, VERBOSE)
select s_name, s_address from supplier, nation where s_suppkey in ( select ps_suppkey from partsupp where ps_partkey in ( select p_partkey from part where p_name like 'green%' ) and ps_availqty > ( select 0.5 * sum(l_quantity) from lineitem where l_partkey = ps_partkey and l_suppkey = ps_suppkey and l_shipdate >= date '1997-01-01' and l_shipdate < date '1997-01-01' + interval '1 year' ) ) and s_nationkey = n_nationkey and n_name =  'VIETNAM' order by s_name;
EXPLAIN (FORMAT JSON, ANALYZE, VERBOSE)
select s_name, s_address from supplier, nation where s_suppkey in ( select ps_suppkey from partsupp where ps_partkey in ( select p_partkey from part where p_name like 'rosy%' ) and ps_availqty > ( select 0.5 * sum(l_quantity) from lineitem where l_partkey = ps_partkey and l_suppkey = ps_suppkey and l_shipdate >= date '1996-01-01' and l_shipdate < date '1996-01-01' + interval '1 year' ) ) and s_nationkey = n_nationkey and n_name =  'IRAN' order by s_name;
EXPLAIN (FORMAT JSON, ANALYZE, VERBOSE)
select s_name, s_address from supplier, nation where s_suppkey in ( select ps_suppkey from partsupp where ps_partkey in ( select p_partkey from part where p_name like 'cornflower%' ) and ps_availqty > ( select 0.5 * sum(l_quantity) from lineitem where l_partkey = ps_partkey and l_suppkey = ps_suppkey and l_shipdate >= date '1994-01-01' and l_shipdate < date '1994-01-01' + interval '1 year' ) ) and s_nationkey = n_nationkey and n_name =  'ALGERIA' order by s_name;
EXPLAIN (FORMAT JSON, ANALYZE, VERBOSE)
select s_name, s_address from supplier, nation where s_suppkey in ( select ps_suppkey from partsupp where ps_partkey in ( select p_partkey from part where p_name like 'navy%' ) and ps_availqty > ( select 0.5 * sum(l_quantity) from lineitem where l_partkey = ps_partkey and l_suppkey = ps_suppkey and l_shipdate >= date '1993-01-01' and l_shipdate < date '1993-01-01' + interval '1 year' ) ) and s_nationkey = n_nationkey and n_name =  'MOROCCO' order by s_name;
EXPLAIN (FORMAT JSON, ANALYZE, VERBOSE)
select s_name, s_address from supplier, nation where s_suppkey in ( select ps_suppkey from partsupp where ps_partkey in ( select p_partkey from part where p_name like 'aquamarine%' ) and ps_availqty > ( select 0.5 * sum(l_quantity) from lineitem where l_partkey = ps_partkey and l_suppkey = ps_suppkey and l_shipdate >= date '1996-01-01' and l_shipdate < date '1996-01-01' + interval '1 year' ) ) and s_nationkey = n_nationkey and n_name =  'ETHIOPIA' order by s_name;
EXPLAIN (FORMAT JSON, ANALYZE, VERBOSE)
select s_name, s_address from supplier, nation where s_suppkey in ( select ps_suppkey from partsupp where ps_partkey in ( select p_partkey from part where p_name like 'lavender%' ) and ps_availqty > ( select 0.5 * sum(l_quantity) from lineitem where l_partkey = ps_partkey and l_suppkey = ps_suppkey and l_shipdate >= date '1995-01-01' and l_shipdate < date '1995-01-01' + interval '1 year' ) ) and s_nationkey = n_nationkey and n_name =  'ROMANIA' order by s_name;
EXPLAIN (FORMAT JSON, ANALYZE, VERBOSE)
select s_name, s_address from supplier, nation where s_suppkey in ( select ps_suppkey from partsupp where ps_partkey in ( select p_partkey from part where p_name like 'slate%' ) and ps_availqty > ( select 0.5 * sum(l_quantity) from lineitem where l_partkey = ps_partkey and l_suppkey = ps_suppkey and l_shipdate >= date '1993-01-01' and l_shipdate < date '1993-01-01' + interval '1 year' ) ) and s_nationkey = n_nationkey and n_name =  'INDONESIA' order by s_name;
EXPLAIN (FORMAT JSON, ANALYZE, VERBOSE)
select s_name, s_address from supplier, nation where s_suppkey in ( select ps_suppkey from partsupp where ps_partkey in ( select p_partkey from part where p_name like 'drab%' ) and ps_availqty > ( select 0.5 * sum(l_quantity) from lineitem where l_partkey = ps_partkey and l_suppkey = ps_suppkey and l_shipdate >= date '1996-01-01' and l_shipdate < date '1996-01-01' + interval '1 year' ) ) and s_nationkey = n_nationkey and n_name =  'UNITED STATES' order by s_name;
EXPLAIN (FORMAT JSON, ANALYZE, VERBOSE)
select s_name, s_address from supplier, nation where s_suppkey in ( select ps_suppkey from partsupp where ps_partkey in ( select p_partkey from part where p_name like 'pink%' ) and ps_availqty > ( select 0.5 * sum(l_quantity) from lineitem where l_partkey = ps_partkey and l_suppkey = ps_suppkey and l_shipdate >= date '1995-01-01' and l_shipdate < date '1995-01-01' + interval '1 year' ) ) and s_nationkey = n_nationkey and n_name =  'JORDAN' order by s_name;
EXPLAIN (FORMAT JSON, ANALYZE, VERBOSE)
select s_name, s_address from supplier, nation where s_suppkey in ( select ps_suppkey from partsupp where ps_partkey in ( select p_partkey from part where p_name like 'brown%' ) and ps_availqty > ( select 0.5 * sum(l_quantity) from lineitem where l_partkey = ps_partkey and l_suppkey = ps_suppkey and l_shipdate >= date '1993-01-01' and l_shipdate < date '1993-01-01' + interval '1 year' ) ) and s_nationkey = n_nationkey and n_name =  'CANADA' order by s_name;
EXPLAIN (FORMAT JSON, ANALYZE, VERBOSE)
select s_name, s_address from supplier, nation where s_suppkey in ( select ps_suppkey from partsupp where ps_partkey in ( select p_partkey from part where p_name like 'medium%' ) and ps_availqty > ( select 0.5 * sum(l_quantity) from lineitem where l_partkey = ps_partkey and l_suppkey = ps_suppkey and l_shipdate >= date '1997-01-01' and l_shipdate < date '1997-01-01' + interval '1 year' ) ) and s_nationkey = n_nationkey and n_name =  'CHINA' order by s_name;
EXPLAIN (FORMAT JSON, ANALYZE, VERBOSE)
select s_name, s_address from supplier, nation where s_suppkey in ( select ps_suppkey from partsupp where ps_partkey in ( select p_partkey from part where p_name like 'turquoise%' ) and ps_availqty > ( select 0.5 * sum(l_quantity) from lineitem where l_partkey = ps_partkey and l_suppkey = ps_suppkey and l_shipdate >= date '1995-01-01' and l_shipdate < date '1995-01-01' + interval '1 year' ) ) and s_nationkey = n_nationkey and n_name =  'INDIA' order by s_name;
EXPLAIN (FORMAT JSON, ANALYZE, VERBOSE)
select s_name, s_address from supplier, nation where s_suppkey in ( select ps_suppkey from partsupp where ps_partkey in ( select p_partkey from part where p_name like 'green%' ) and ps_availqty > ( select 0.5 * sum(l_quantity) from lineitem where l_partkey = ps_partkey and l_suppkey = ps_suppkey and l_shipdate >= date '1994-01-01' and l_shipdate < date '1994-01-01' + interval '1 year' ) ) and s_nationkey = n_nationkey and n_name =  'RUSSIA' order by s_name;
EXPLAIN (FORMAT JSON, ANALYZE, VERBOSE)
select s_name, s_address from supplier, nation where s_suppkey in ( select ps_suppkey from partsupp where ps_partkey in ( select p_partkey from part where p_name like 'royal%' ) and ps_availqty > ( select 0.5 * sum(l_quantity) from lineitem where l_partkey = ps_partkey and l_suppkey = ps_suppkey and l_shipdate >= date '1997-01-01' and l_shipdate < date '1997-01-01' + interval '1 year' ) ) and s_nationkey = n_nationkey and n_name =  'JAPAN' order by s_name;
EXPLAIN (FORMAT JSON, ANALYZE, VERBOSE)
select s_name, s_address from supplier, nation where s_suppkey in ( select ps_suppkey from partsupp where ps_partkey in ( select p_partkey from part where p_name like 'cornsilk%' ) and ps_availqty > ( select 0.5 * sum(l_quantity) from lineitem where l_partkey = ps_partkey and l_suppkey = ps_suppkey and l_shipdate >= date '1995-01-01' and l_shipdate < date '1995-01-01' + interval '1 year' ) ) and s_nationkey = n_nationkey and n_name =  'BRAZIL' order by s_name;
EXPLAIN (FORMAT JSON, ANALYZE, VERBOSE)
select s_name, s_address from supplier, nation where s_suppkey in ( select ps_suppkey from partsupp where ps_partkey in ( select p_partkey from part where p_name like 'olive%' ) and ps_availqty > ( select 0.5 * sum(l_quantity) from lineitem where l_partkey = ps_partkey and l_suppkey = ps_suppkey and l_shipdate >= date '1994-01-01' and l_shipdate < date '1994-01-01' + interval '1 year' ) ) and s_nationkey = n_nationkey and n_name =  'PERU' order by s_name;
EXPLAIN (FORMAT JSON, ANALYZE, VERBOSE)
select s_name, s_address from supplier, nation where s_suppkey in ( select ps_suppkey from partsupp where ps_partkey in ( select p_partkey from part where p_name like 'azure%' ) and ps_availqty > ( select 0.5 * sum(l_quantity) from lineitem where l_partkey = ps_partkey and l_suppkey = ps_suppkey and l_shipdate >= date '1997-01-01' and l_shipdate < date '1997-01-01' + interval '1 year' ) ) and s_nationkey = n_nationkey and n_name =  'FRANCE' order by s_name;
EXPLAIN (FORMAT JSON, ANALYZE, VERBOSE)
select s_name, s_address from supplier, nation where s_suppkey in ( select ps_suppkey from partsupp where ps_partkey in ( select p_partkey from part where p_name like 'lawn%' ) and ps_availqty > ( select 0.5 * sum(l_quantity) from lineitem where l_partkey = ps_partkey and l_suppkey = ps_suppkey and l_shipdate >= date '1996-01-01' and l_shipdate < date '1996-01-01' + interval '1 year' ) ) and s_nationkey = n_nationkey and n_name =  'VIETNAM' order by s_name;
EXPLAIN (FORMAT JSON, ANALYZE, VERBOSE)
select s_name, s_address from supplier, nation where s_suppkey in ( select ps_suppkey from partsupp where ps_partkey in ( select p_partkey from part where p_name like 'smoke%' ) and ps_availqty > ( select 0.5 * sum(l_quantity) from lineitem where l_partkey = ps_partkey and l_suppkey = ps_suppkey and l_shipdate >= date '1994-01-01' and l_shipdate < date '1994-01-01' + interval '1 year' ) ) and s_nationkey = n_nationkey and n_name =  'IRAQ' order by s_name;
EXPLAIN (FORMAT JSON, ANALYZE, VERBOSE)
select s_name, s_address from supplier, nation where s_suppkey in ( select ps_suppkey from partsupp where ps_partkey in ( select p_partkey from part where p_name like 'firebrick%' ) and ps_availqty > ( select 0.5 * sum(l_quantity) from lineitem where l_partkey = ps_partkey and l_suppkey = ps_suppkey and l_shipdate >= date '1993-01-01' and l_shipdate < date '1993-01-01' + interval '1 year' ) ) and s_nationkey = n_nationkey and n_name =  'ALGERIA' order by s_name;
EXPLAIN (FORMAT JSON, ANALYZE, VERBOSE)
select s_name, s_address from supplier, nation where s_suppkey in ( select ps_suppkey from partsupp where ps_partkey in ( select p_partkey from part where p_name like 'plum%' ) and ps_availqty > ( select 0.5 * sum(l_quantity) from lineitem where l_partkey = ps_partkey and l_suppkey = ps_suppkey and l_shipdate >= date '1996-01-01' and l_shipdate < date '1996-01-01' + interval '1 year' ) ) and s_nationkey = n_nationkey and n_name =  'MOROCCO' order by s_name;
EXPLAIN (FORMAT JSON, ANALYZE, VERBOSE)
select s_name, s_address from supplier, nation where s_suppkey in ( select ps_suppkey from partsupp where ps_partkey in ( select p_partkey from part where p_name like 'burlywood%' ) and ps_availqty > ( select 0.5 * sum(l_quantity) from lineitem where l_partkey = ps_partkey and l_suppkey = ps_suppkey and l_shipdate >= date '1994-01-01' and l_shipdate < date '1994-01-01' + interval '1 year' ) ) and s_nationkey = n_nationkey and n_name =  'ETHIOPIA' order by s_name;
EXPLAIN (FORMAT JSON, ANALYZE, VERBOSE)
select s_name, s_address from supplier, nation where s_suppkey in ( select ps_suppkey from partsupp where ps_partkey in ( select p_partkey from part where p_name like 'metallic%' ) and ps_availqty > ( select 0.5 * sum(l_quantity) from lineitem where l_partkey = ps_partkey and l_suppkey = ps_suppkey and l_shipdate >= date '1993-01-01' and l_shipdate < date '1993-01-01' + interval '1 year' ) ) and s_nationkey = n_nationkey and n_name =  'SAUDI ARABIA' order by s_name;
EXPLAIN (FORMAT JSON, ANALYZE, VERBOSE)
select s_name, s_address from supplier, nation where s_suppkey in ( select ps_suppkey from partsupp where ps_partkey in ( select p_partkey from part where p_name like 'violet%' ) and ps_availqty > ( select 0.5 * sum(l_quantity) from lineitem where l_partkey = ps_partkey and l_suppkey = ps_suppkey and l_shipdate >= date '1996-01-01' and l_shipdate < date '1996-01-01' + interval '1 year' ) ) and s_nationkey = n_nationkey and n_name =  'INDONESIA' order by s_name;
EXPLAIN (FORMAT JSON, ANALYZE, VERBOSE)
select s_name, s_address from supplier, nation where s_suppkey in ( select ps_suppkey from partsupp where ps_partkey in ( select p_partkey from part where p_name like 'grey%' ) and ps_availqty > ( select 0.5 * sum(l_quantity) from lineitem where l_partkey = ps_partkey and l_suppkey = ps_suppkey and l_shipdate >= date '1995-01-01' and l_shipdate < date '1995-01-01' + interval '1 year' ) ) and s_nationkey = n_nationkey and n_name =  'UNITED STATES' order by s_name;
EXPLAIN (FORMAT JSON, ANALYZE, VERBOSE)
select s_name, s_address from supplier, nation where s_suppkey in ( select ps_suppkey from partsupp where ps_partkey in ( select p_partkey from part where p_name like 'saddle%' ) and ps_availqty > ( select 0.5 * sum(l_quantity) from lineitem where l_partkey = ps_partkey and l_suppkey = ps_suppkey and l_shipdate >= date '1993-01-01' and l_shipdate < date '1993-01-01' + interval '1 year' ) ) and s_nationkey = n_nationkey and n_name =  'KENYA' order by s_name;
EXPLAIN (FORMAT JSON, ANALYZE, VERBOSE)
select s_name, s_address from supplier, nation where s_suppkey in ( select ps_suppkey from partsupp where ps_partkey in ( select p_partkey from part where p_name like 'cream%' ) and ps_availqty > ( select 0.5 * sum(l_quantity) from lineitem where l_partkey = ps_partkey and l_suppkey = ps_suppkey and l_shipdate >= date '1997-01-01' and l_shipdate < date '1997-01-01' + interval '1 year' ) ) and s_nationkey = n_nationkey and n_name =  'EGYPT' order by s_name;
EXPLAIN (FORMAT JSON, ANALYZE, VERBOSE)
select s_name, s_address from supplier, nation where s_suppkey in ( select ps_suppkey from partsupp where ps_partkey in ( select p_partkey from part where p_name like 'orange%' ) and ps_availqty > ( select 0.5 * sum(l_quantity) from lineitem where l_partkey = ps_partkey and l_suppkey = ps_suppkey and l_shipdate >= date '1995-01-01' and l_shipdate < date '1995-01-01' + interval '1 year' ) ) and s_nationkey = n_nationkey and n_name =  'CHINA' order by s_name;
EXPLAIN (FORMAT JSON, ANALYZE, VERBOSE)
select s_name, s_address from supplier, nation where s_suppkey in ( select ps_suppkey from partsupp where ps_partkey in ( select p_partkey from part where p_name like 'beige%' ) and ps_availqty > ( select 0.5 * sum(l_quantity) from lineitem where l_partkey = ps_partkey and l_suppkey = ps_suppkey and l_shipdate >= date '1994-01-01' and l_shipdate < date '1994-01-01' + interval '1 year' ) ) and s_nationkey = n_nationkey and n_name =  'INDIA' order by s_name;
EXPLAIN (FORMAT JSON, ANALYZE, VERBOSE)
select s_name, s_address from supplier, nation where s_suppkey in ( select ps_suppkey from partsupp where ps_partkey in ( select p_partkey from part where p_name like 'lawn%' ) and ps_availqty > ( select 0.5 * sum(l_quantity) from lineitem where l_partkey = ps_partkey and l_suppkey = ps_suppkey and l_shipdate >= date '1997-01-01' and l_shipdate < date '1997-01-01' + interval '1 year' ) ) and s_nationkey = n_nationkey and n_name =  'UNITED KINGDOM' order by s_name;
EXPLAIN (FORMAT JSON, ANALYZE, VERBOSE)
select s_name, s_address from supplier, nation where s_suppkey in ( select ps_suppkey from partsupp where ps_partkey in ( select p_partkey from part where p_name like 'snow%' ) and ps_availqty > ( select 0.5 * sum(l_quantity) from lineitem where l_partkey = ps_partkey and l_suppkey = ps_suppkey and l_shipdate >= date '1995-01-01' and l_shipdate < date '1995-01-01' + interval '1 year' ) ) and s_nationkey = n_nationkey and n_name =  'JAPAN' order by s_name;
EXPLAIN (FORMAT JSON, ANALYZE, VERBOSE)
select s_name, s_address from supplier, nation where s_suppkey in ( select ps_suppkey from partsupp where ps_partkey in ( select p_partkey from part where p_name like 'floral%' ) and ps_availqty > ( select 0.5 * sum(l_quantity) from lineitem where l_partkey = ps_partkey and l_suppkey = ps_suppkey and l_shipdate >= date '1994-01-01' and l_shipdate < date '1994-01-01' + interval '1 year' ) ) and s_nationkey = n_nationkey and n_name =  'BRAZIL' order by s_name;
EXPLAIN (FORMAT JSON, ANALYZE, VERBOSE)
select s_name, s_address from supplier, nation where s_suppkey in ( select ps_suppkey from partsupp where ps_partkey in ( select p_partkey from part where p_name like 'powder%' ) and ps_availqty > ( select 0.5 * sum(l_quantity) from lineitem where l_partkey = ps_partkey and l_suppkey = ps_suppkey and l_shipdate >= date '1997-01-01' and l_shipdate < date '1997-01-01' + interval '1 year' ) ) and s_nationkey = n_nationkey and n_name =  'PERU' order by s_name;
EXPLAIN (FORMAT JSON, ANALYZE, VERBOSE)
select s_name, s_address from supplier, nation where s_suppkey in ( select ps_suppkey from partsupp where ps_partkey in ( select p_partkey from part where p_name like 'burnished%' ) and ps_availqty > ( select 0.5 * sum(l_quantity) from lineitem where l_partkey = ps_partkey and l_suppkey = ps_suppkey and l_shipdate >= date '1996-01-01' and l_shipdate < date '1996-01-01' + interval '1 year' ) ) and s_nationkey = n_nationkey and n_name =  'GERMANY' order by s_name;
EXPLAIN (FORMAT JSON, ANALYZE, VERBOSE)
select s_name, s_address from supplier, nation where s_suppkey in ( select ps_suppkey from partsupp where ps_partkey in ( select p_partkey from part where p_name like 'metallic%' ) and ps_availqty > ( select 0.5 * sum(l_quantity) from lineitem where l_partkey = ps_partkey and l_suppkey = ps_suppkey and l_shipdate >= date '1994-01-01' and l_shipdate < date '1994-01-01' + interval '1 year' ) ) and s_nationkey = n_nationkey and n_name =  'VIETNAM' order by s_name;
EXPLAIN (FORMAT JSON, ANALYZE, VERBOSE)
select s_name, s_address from supplier, nation where s_suppkey in ( select ps_suppkey from partsupp where ps_partkey in ( select p_partkey from part where p_name like 'wheat%' ) and ps_availqty > ( select 0.5 * sum(l_quantity) from lineitem where l_partkey = ps_partkey and l_suppkey = ps_suppkey and l_shipdate >= date '1993-01-01' and l_shipdate < date '1993-01-01' + interval '1 year' ) ) and s_nationkey = n_nationkey and n_name =  'IRAQ' order by s_name;
EXPLAIN (FORMAT JSON, ANALYZE, VERBOSE)
select s_name, s_address from supplier, nation where s_suppkey in ( select ps_suppkey from partsupp where ps_partkey in ( select p_partkey from part where p_name like 'honeydew%' ) and ps_availqty > ( select 0.5 * sum(l_quantity) from lineitem where l_partkey = ps_partkey and l_suppkey = ps_suppkey and l_shipdate >= date '1996-01-01' and l_shipdate < date '1996-01-01' + interval '1 year' ) ) and s_nationkey = n_nationkey and n_name =  'ARGENTINA' order by s_name;
EXPLAIN (FORMAT JSON, ANALYZE, VERBOSE)
select s_name, s_address from supplier, nation where s_suppkey in ( select ps_suppkey from partsupp where ps_partkey in ( select p_partkey from part where p_name like 'salmon%' ) and ps_availqty > ( select 0.5 * sum(l_quantity) from lineitem where l_partkey = ps_partkey and l_suppkey = ps_suppkey and l_shipdate >= date '1994-01-01' and l_shipdate < date '1994-01-01' + interval '1 year' ) ) and s_nationkey = n_nationkey and n_name =  'MOROCCO' order by s_name;
EXPLAIN (FORMAT JSON, ANALYZE, VERBOSE)
select s_name, s_address from supplier, nation where s_suppkey in ( select ps_suppkey from partsupp where ps_partkey in ( select p_partkey from part where p_name like 'cyan%' ) and ps_availqty > ( select 0.5 * sum(l_quantity) from lineitem where l_partkey = ps_partkey and l_suppkey = ps_suppkey and l_shipdate >= date '1993-01-01' and l_shipdate < date '1993-01-01' + interval '1 year' ) ) and s_nationkey = n_nationkey and n_name =  'ETHIOPIA' order by s_name;
EXPLAIN (FORMAT JSON, ANALYZE, VERBOSE)
select s_name, s_address from supplier, nation where s_suppkey in ( select ps_suppkey from partsupp where ps_partkey in ( select p_partkey from part where p_name like 'orchid%' ) and ps_availqty > ( select 0.5 * sum(l_quantity) from lineitem where l_partkey = ps_partkey and l_suppkey = ps_suppkey and l_shipdate >= date '1996-01-01' and l_shipdate < date '1996-01-01' + interval '1 year' ) ) and s_nationkey = n_nationkey and n_name =  'SAUDI ARABIA' order by s_name;
EXPLAIN (FORMAT JSON, ANALYZE, VERBOSE)
select s_name, s_address from supplier, nation where s_suppkey in ( select ps_suppkey from partsupp where ps_partkey in ( select p_partkey from part where p_name like 'bisque%' ) and ps_availqty > ( select 0.5 * sum(l_quantity) from lineitem where l_partkey = ps_partkey and l_suppkey = ps_suppkey and l_shipdate >= date '1995-01-01' and l_shipdate < date '1995-01-01' + interval '1 year' ) ) and s_nationkey = n_nationkey and n_name =  'IRAN' order by s_name;
EXPLAIN (FORMAT JSON, ANALYZE, VERBOSE)
select s_name, s_address from supplier, nation where s_suppkey in ( select ps_suppkey from partsupp where ps_partkey in ( select p_partkey from part where p_name like 'lemon%' ) and ps_availqty > ( select 0.5 * sum(l_quantity) from lineitem where l_partkey = ps_partkey and l_suppkey = ps_suppkey and l_shipdate >= date '1993-01-01' and l_shipdate < date '1993-01-01' + interval '1 year' ) ) and s_nationkey = n_nationkey and n_name =  'UNITED STATES' order by s_name;
EXPLAIN (FORMAT JSON, ANALYZE, VERBOSE)
select s_name, s_address from supplier, nation where s_suppkey in ( select ps_suppkey from partsupp where ps_partkey in ( select p_partkey from part where p_name like 'spring%' ) and ps_availqty > ( select 0.5 * sum(l_quantity) from lineitem where l_partkey = ps_partkey and l_suppkey = ps_suppkey and l_shipdate >= date '1997-01-01' and l_shipdate < date '1997-01-01' + interval '1 year' ) ) and s_nationkey = n_nationkey and n_name =  'KENYA' order by s_name;
EXPLAIN (FORMAT JSON, ANALYZE, VERBOSE)
select s_name, s_address from supplier, nation where s_suppkey in ( select ps_suppkey from partsupp where ps_partkey in ( select p_partkey from part where p_name like 'forest%' ) and ps_availqty > ( select 0.5 * sum(l_quantity) from lineitem where l_partkey = ps_partkey and l_suppkey = ps_suppkey and l_shipdate >= date '1995-01-01' and l_shipdate < date '1995-01-01' + interval '1 year' ) ) and s_nationkey = n_nationkey and n_name =  'EGYPT' order by s_name;
EXPLAIN (FORMAT JSON, ANALYZE, VERBOSE)
select s_name, s_address from supplier, nation where s_suppkey in ( select ps_suppkey from partsupp where ps_partkey in ( select p_partkey from part where p_name like 'puff%' ) and ps_availqty > ( select 0.5 * sum(l_quantity) from lineitem where l_partkey = ps_partkey and l_suppkey = ps_suppkey and l_shipdate >= date '1993-01-01' and l_shipdate < date '1993-01-01' + interval '1 year' ) ) and s_nationkey = n_nationkey and n_name =  'ROMANIA' order by s_name;
EXPLAIN (FORMAT JSON, ANALYZE, VERBOSE)
select s_name, s_address from supplier, nation where s_suppkey in ( select ps_suppkey from partsupp where ps_partkey in ( select p_partkey from part where p_name like 'chartreuse%' ) and ps_availqty > ( select 0.5 * sum(l_quantity) from lineitem where l_partkey = ps_partkey and l_suppkey = ps_suppkey and l_shipdate >= date '1997-01-01' and l_shipdate < date '1997-01-01' + interval '1 year' ) ) and s_nationkey = n_nationkey and n_name =  'INDIA' order by s_name;
EXPLAIN (FORMAT JSON, ANALYZE, VERBOSE)
select s_name, s_address from supplier, nation where s_suppkey in ( select ps_suppkey from partsupp where ps_partkey in ( select p_partkey from part where p_name like 'midnight%' ) and ps_availqty > ( select 0.5 * sum(l_quantity) from lineitem where l_partkey = ps_partkey and l_suppkey = ps_suppkey and l_shipdate >= date '1995-01-01' and l_shipdate < date '1995-01-01' + interval '1 year' ) ) and s_nationkey = n_nationkey and n_name =  'UNITED KINGDOM' order by s_name;
EXPLAIN (FORMAT JSON, ANALYZE, VERBOSE)
select s_name, s_address from supplier, nation where s_suppkey in ( select ps_suppkey from partsupp where ps_partkey in ( select p_partkey from part where p_name like 'white%' ) and ps_availqty > ( select 0.5 * sum(l_quantity) from lineitem where l_partkey = ps_partkey and l_suppkey = ps_suppkey and l_shipdate >= date '1994-01-01' and l_shipdate < date '1994-01-01' + interval '1 year' ) ) and s_nationkey = n_nationkey and n_name =  'JORDAN' order by s_name;
EXPLAIN (FORMAT JSON, ANALYZE, VERBOSE)
select s_name, s_address from supplier, nation where s_suppkey in ( select ps_suppkey from partsupp where ps_partkey in ( select p_partkey from part where p_name like 'hot%' ) and ps_availqty > ( select 0.5 * sum(l_quantity) from lineitem where l_partkey = ps_partkey and l_suppkey = ps_suppkey and l_shipdate >= date '1997-01-01' and l_shipdate < date '1997-01-01' + interval '1 year' ) ) and s_nationkey = n_nationkey and n_name =  'BRAZIL' order by s_name;
EXPLAIN (FORMAT JSON, ANALYZE, VERBOSE)
select s_name, s_address from supplier, nation where s_suppkey in ( select ps_suppkey from partsupp where ps_partkey in ( select p_partkey from part where p_name like 'sandy%' ) and ps_availqty > ( select 0.5 * sum(l_quantity) from lineitem where l_partkey = ps_partkey and l_suppkey = ps_suppkey and l_shipdate >= date '1996-01-01' and l_shipdate < date '1996-01-01' + interval '1 year' ) ) and s_nationkey = n_nationkey and n_name =  'PERU' order by s_name;
EXPLAIN (FORMAT JSON, ANALYZE, VERBOSE)
select s_name, s_address from supplier, nation where s_suppkey in ( select ps_suppkey from partsupp where ps_partkey in ( select p_partkey from part where p_name like 'dark%' ) and ps_availqty > ( select 0.5 * sum(l_quantity) from lineitem where l_partkey = ps_partkey and l_suppkey = ps_suppkey and l_shipdate >= date '1994-01-01' and l_shipdate < date '1994-01-01' + interval '1 year' ) ) and s_nationkey = n_nationkey and n_name =  'GERMANY' order by s_name;
EXPLAIN (FORMAT JSON, ANALYZE, VERBOSE)
select s_name, s_address from supplier, nation where s_suppkey in ( select ps_suppkey from partsupp where ps_partkey in ( select p_partkey from part where p_name like 'orchid%' ) and ps_availqty > ( select 0.5 * sum(l_quantity) from lineitem where l_partkey = ps_partkey and l_suppkey = ps_suppkey and l_shipdate >= date '1993-01-01' and l_shipdate < date '1993-01-01' + interval '1 year' ) ) and s_nationkey = n_nationkey and n_name =  'RUSSIA' order by s_name;
EXPLAIN (FORMAT JSON, ANALYZE, VERBOSE)
select s_name, s_address from supplier, nation where s_suppkey in ( select ps_suppkey from partsupp where ps_partkey in ( select p_partkey from part where p_name like 'black%' ) and ps_availqty > ( select 0.5 * sum(l_quantity) from lineitem where l_partkey = ps_partkey and l_suppkey = ps_suppkey and l_shipdate >= date '1996-01-01' and l_shipdate < date '1996-01-01' + interval '1 year' ) ) and s_nationkey = n_nationkey and n_name =  'IRAQ' order by s_name;
EXPLAIN (FORMAT JSON, ANALYZE, VERBOSE)
select s_name, s_address from supplier, nation where s_suppkey in ( select ps_suppkey from partsupp where ps_partkey in ( select p_partkey from part where p_name like 'light%' ) and ps_availqty > ( select 0.5 * sum(l_quantity) from lineitem where l_partkey = ps_partkey and l_suppkey = ps_suppkey and l_shipdate >= date '1994-01-01' and l_shipdate < date '1994-01-01' + interval '1 year' ) ) and s_nationkey = n_nationkey and n_name =  'ARGENTINA' order by s_name;
EXPLAIN (FORMAT JSON, ANALYZE, VERBOSE)
select s_name, s_address from supplier, nation where s_suppkey in ( select ps_suppkey from partsupp where ps_partkey in ( select p_partkey from part where p_name like 'steel%' ) and ps_availqty > ( select 0.5 * sum(l_quantity) from lineitem where l_partkey = ps_partkey and l_suppkey = ps_suppkey and l_shipdate >= date '1993-01-01' and l_shipdate < date '1993-01-01' + interval '1 year' ) ) and s_nationkey = n_nationkey and n_name =  'MOZAMBIQUE' order by s_name;
EXPLAIN (FORMAT JSON, ANALYZE, VERBOSE)
select s_name, s_address from supplier, nation where s_suppkey in ( select ps_suppkey from partsupp where ps_partkey in ( select p_partkey from part where p_name like 'frosted%' ) and ps_availqty > ( select 0.5 * sum(l_quantity) from lineitem where l_partkey = ps_partkey and l_suppkey = ps_suppkey and l_shipdate >= date '1996-01-01' and l_shipdate < date '1996-01-01' + interval '1 year' ) ) and s_nationkey = n_nationkey and n_name =  'FRANCE' order by s_name;
EXPLAIN (FORMAT JSON, ANALYZE, VERBOSE)
select s_name, s_address from supplier, nation where s_suppkey in ( select ps_suppkey from partsupp where ps_partkey in ( select p_partkey from part where p_name like 'puff%' ) and ps_availqty > ( select 0.5 * sum(l_quantity) from lineitem where l_partkey = ps_partkey and l_suppkey = ps_suppkey and l_shipdate >= date '1995-01-01' and l_shipdate < date '1995-01-01' + interval '1 year' ) ) and s_nationkey = n_nationkey and n_name =  'SAUDI ARABIA' order by s_name;
EXPLAIN (FORMAT JSON, ANALYZE, VERBOSE)
select s_name, s_address from supplier, nation where s_suppkey in ( select ps_suppkey from partsupp where ps_partkey in ( select p_partkey from part where p_name like 'chiffon%' ) and ps_availqty > ( select 0.5 * sum(l_quantity) from lineitem where l_partkey = ps_partkey and l_suppkey = ps_suppkey and l_shipdate >= date '1993-01-01' and l_shipdate < date '1993-01-01' + interval '1 year' ) ) and s_nationkey = n_nationkey and n_name =  'IRAN' order by s_name;
EXPLAIN (FORMAT JSON, ANALYZE, VERBOSE)
select s_name, s_address from supplier, nation where s_suppkey in ( select ps_suppkey from partsupp where ps_partkey in ( select p_partkey from part where p_name like 'mint%' ) and ps_availqty > ( select 0.5 * sum(l_quantity) from lineitem where l_partkey = ps_partkey and l_suppkey = ps_suppkey and l_shipdate >= date '1997-01-01' and l_shipdate < date '1997-01-01' + interval '1 year' ) ) and s_nationkey = n_nationkey and n_name =  'ALGERIA' order by s_name;
EXPLAIN (FORMAT JSON, ANALYZE, VERBOSE)
select s_name, s_address from supplier, nation where s_suppkey in ( select ps_suppkey from partsupp where ps_partkey in ( select p_partkey from part where p_name like 'yellow%' ) and ps_availqty > ( select 0.5 * sum(l_quantity) from lineitem where l_partkey = ps_partkey and l_suppkey = ps_suppkey and l_shipdate >= date '1995-01-01' and l_shipdate < date '1995-01-01' + interval '1 year' ) ) and s_nationkey = n_nationkey and n_name =  'KENYA' order by s_name;
EXPLAIN (FORMAT JSON, ANALYZE, VERBOSE)
select s_name, s_address from supplier, nation where s_suppkey in ( select ps_suppkey from partsupp where ps_partkey in ( select p_partkey from part where p_name like 'indian%' ) and ps_availqty > ( select 0.5 * sum(l_quantity) from lineitem where l_partkey = ps_partkey and l_suppkey = ps_suppkey and l_shipdate >= date '1993-01-01' and l_shipdate < date '1993-01-01' + interval '1 year' ) ) and s_nationkey = n_nationkey and n_name =  'EGYPT' order by s_name;
EXPLAIN (FORMAT JSON, ANALYZE, VERBOSE)
select s_name, s_address from supplier, nation where s_suppkey in ( select ps_suppkey from partsupp where ps_partkey in ( select p_partkey from part where p_name like 'seashell%' ) and ps_availqty > ( select 0.5 * sum(l_quantity) from lineitem where l_partkey = ps_partkey and l_suppkey = ps_suppkey and l_shipdate >= date '1997-01-01' and l_shipdate < date '1997-01-01' + interval '1 year' ) ) and s_nationkey = n_nationkey and n_name =  'ROMANIA' order by s_name;
EXPLAIN (FORMAT JSON, ANALYZE, VERBOSE)
select s_name, s_address from supplier, nation where s_suppkey in ( select ps_suppkey from partsupp where ps_partkey in ( select p_partkey from part where p_name like 'deep%' ) and ps_availqty > ( select 0.5 * sum(l_quantity) from lineitem where l_partkey = ps_partkey and l_suppkey = ps_suppkey and l_shipdate >= date '1995-01-01' and l_shipdate < date '1995-01-01' + interval '1 year' ) ) and s_nationkey = n_nationkey and n_name =  'INDONESIA' order by s_name;
EXPLAIN (FORMAT JSON, ANALYZE, VERBOSE)
select s_name, s_address from supplier, nation where s_suppkey in ( select ps_suppkey from partsupp where ps_partkey in ( select p_partkey from part where p_name like 'pale%' ) and ps_availqty > ( select 0.5 * sum(l_quantity) from lineitem where l_partkey = ps_partkey and l_suppkey = ps_suppkey and l_shipdate >= date '1994-01-01' and l_shipdate < date '1994-01-01' + interval '1 year' ) ) and s_nationkey = n_nationkey and n_name =  'UNITED KINGDOM' order by s_name;
EXPLAIN (FORMAT JSON, ANALYZE, VERBOSE)
select s_name, s_address from supplier, nation where s_suppkey in ( select ps_suppkey from partsupp where ps_partkey in ( select p_partkey from part where p_name like 'blanched%' ) and ps_availqty > ( select 0.5 * sum(l_quantity) from lineitem where l_partkey = ps_partkey and l_suppkey = ps_suppkey and l_shipdate >= date '1997-01-01' and l_shipdate < date '1997-01-01' + interval '1 year' ) ) and s_nationkey = n_nationkey and n_name =  'JORDAN' order by s_name;
EXPLAIN (FORMAT JSON, ANALYZE, VERBOSE)
select s_name, s_address from supplier, nation where s_suppkey in ( select ps_suppkey from partsupp where ps_partkey in ( select p_partkey from part where p_name like 'lime%' ) and ps_availqty > ( select 0.5 * sum(l_quantity) from lineitem where l_partkey = ps_partkey and l_suppkey = ps_suppkey and l_shipdate >= date '1996-01-01' and l_shipdate < date '1996-01-01' + interval '1 year' ) ) and s_nationkey = n_nationkey and n_name =  'CANADA' order by s_name;
EXPLAIN (FORMAT JSON, ANALYZE, VERBOSE)
select s_name, s_address from supplier, nation where s_suppkey in ( select ps_suppkey from partsupp where ps_partkey in ( select p_partkey from part where p_name like 'tan%' ) and ps_availqty > ( select 0.5 * sum(l_quantity) from lineitem where l_partkey = ps_partkey and l_suppkey = ps_suppkey and l_shipdate >= date '1994-01-01' and l_shipdate < date '1994-01-01' + interval '1 year' ) ) and s_nationkey = n_nationkey and n_name =  'PERU' order by s_name;
EXPLAIN (FORMAT JSON, ANALYZE, VERBOSE)
select s_name, s_address from supplier, nation where s_suppkey in ( select ps_suppkey from partsupp where ps_partkey in ( select p_partkey from part where p_name like 'gainsboro%' ) and ps_availqty > ( select 0.5 * sum(l_quantity) from lineitem where l_partkey = ps_partkey and l_suppkey = ps_suppkey and l_shipdate >= date '1997-01-01' and l_shipdate < date '1997-01-01' + interval '1 year' ) ) and s_nationkey = n_nationkey and n_name =  'GERMANY' order by s_name;
EXPLAIN (FORMAT JSON, ANALYZE, VERBOSE)
select s_name, s_address from supplier, nation where s_suppkey in ( select ps_suppkey from partsupp where ps_partkey in ( select p_partkey from part where p_name like 'purple%' ) and ps_availqty > ( select 0.5 * sum(l_quantity) from lineitem where l_partkey = ps_partkey and l_suppkey = ps_suppkey and l_shipdate >= date '1996-01-01' and l_shipdate < date '1996-01-01' + interval '1 year' ) ) and s_nationkey = n_nationkey and n_name =  'RUSSIA' order by s_name;
